export XDG_DATA_HOME="${HOME}"/.local/share
export XDG_CONFIG_HOME="${HOME}"/.config
export XDG_CACHE_HOME="${HOME}"/.cache
export ZDOTDIR="${XDG_CONFIG_HOME}"/zsh
export ZPLUGINDIR="${XDG_DATA_HOME}"/zsh/plugins
export WINEDLLOVERRIDES=winemenubuilder.exe=d
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export VAGRANT_DEFAULT_PROVIDER=libvirt
export LIBVIRT_DEFAULT_URI=qemu:///system
export EDITOR=nvim
export SUDOEDITOR=nvim
export PAGER=less
export VIRTUAL_ENV_DISABLE_PROMPT=1
typeset -U path PATH
path=(
    "${HOME}"/bin
    "${HOME}"/.local/bin
    "${HOME}"/.cargo/bin
    "${XDG_DATA_HOME}"/npm/bin
    "${XDG_DATA_HOME}"/go/bin
    "${XDG_DATA_HOME}"/JetBrains/Toolbox/scripts
    $path
); export PATH
