export ANTIDOTE_GIT_HOME=~/.local/share/antidote
export ZDOTDIR=~/.config/zsh
export ZPLUGINDIR=~/.local/share/zsh/plugins
export EDITOR=nvim
export VISUAL=$EDITOR
export SUDO_EDITOR=$EDITOR
export PAGER=less
export PATH=~/.local/bin:~/.cargo/bin:~/go/bin:~/.local/share/JetBrains/Toolbox/scripts:$PATH
