[ ! -d "${ANTIDOTE_GIT_HOME}" ] && git clone --depth=1 https://github.com/mattmc3/antidote.git "${ANTIDOTE_GIT_HOME}"
source "${ANTIDOTE_GIT_HOME}"/antidote.zsh

ABBR_USER_ABBREVIATIONS_FILE="${ZDOTDIR}"/zabbr

zstyle ':zephyr:plugin:history' 'histfile' ~/.local/state/zsh/history

antidote load "${ZDOTDIR}"/zplugins
